apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[{"apiVersion":"apps.openshift.io/v1alpha1","kind":"ServiceBindingRequest","metadata":{"name":"example-servicebindingrequest"},"spec":{"applicationSelector":{"matchLabels":{"connects-to":"postgres","environment":"production"},"resourceKind":"Deployment"},"backingServiceSelector":{"resourceName":"database.example.org","resourceVersion":"v1alpha1"}}}]'  # yamllint disable-line rule:line-length
    capabilities: Basic Install
    containerImage: quay.io/redhat-developer/openshift-jenkins-operator:v0.0.2
    description: An operator to provide the Jenkins server to support
      automated building, testing, and deploying software.
  name: jenkins-operator.v0.0.2
  namespace: placeholder
spec:
  links:
  - name: Source Code
    url: https://github.com/redhat-developer/openshift-jenkins-operator
  maintainers:
    - email: abenaiss@redhat.com
      name: Akram Ben Aissi
    - email: vbobade@redhat.com
      name: Vibhav Bobade
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - kind: Jenkins
      name: jenkins.jenkins.dev
      version: v1alpha1
      displayName: Jenkins
      description: Installs a Jenkins server instance
  description: An operator to provide the Jenkins server to support
      automated building, testing, and deploying software.
  displayName: Jenkins Operator
  install:
    spec:
      deployments:
      - name: jenkins-operator
        spec:
          replicas: 1
          selector:
            matchLabels:
              name: jenkins-operator
          strategy: {}
          template:
            metadata:
              labels:
                name: jenkins-operator
            spec:
              containers:
              - command:
                - jenkins-operator
                env:
                - name: WATCH_NAMESPACE
                  value: ""
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: OPERATOR_NAME
                  value: jenkins-operator
                image: quay.io/redhat-developer/openshift-jenkins-operator:v0.0.2
                imagePullPolicy: Always
                name: jenkins-operator
                resources: {}
              serviceAccountName: openshift-jenkins-operator
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - pods
          - services
          - endpoints
          - persistentvolumeclaims
          - events
          - configmaps
          - secrets
          verbs:
          - '*'
        - apiGroups:
          - apps
          resources:
          - deployments
          - daemonsets
          - replicasets
          - statefulsets
          verbs:
          - '*'
        - apiGroups:
          - monitoring.coreos.com
          resources:
          - servicemonitors
          verbs:
          - get
          - create
        - apiGroups:
          - apps
          resourceNames:
          - jenkins-operator
          resources:
          - deployments/finalizers
          verbs:
          - update
        - apiGroups:
          - apps.openshift.io
          resources:
          - '*'
          verbs:
          - '*'
        - apiGroups:
          - "*"
          resources:
          - "*"
          verbs:
          - "get"
          - "list"
        serviceAccountName: openshift-jenkins-operator
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  maturity: alpha
  provider:
    name: Red Hat, Inc.
  version: 0.0.2
